app = "TODO_APP_NAME"
primary_region = "TODO_REGION"

[build]
  dockerfile = "server/Dockerfile"

[env]
  PORT = "4000"

[processes]
  app = "node server/dist/index.js"
  cron = "supercronic /app/server/crontab"

[[services]]
  internal_port = 4000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
